services:
  api:
    build:
      context: .
      target: dev
    container_name: camerrideshare_api
    env_file:
      - .env
    environment:
      PORT: ${PORT:-3000}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "pnpm prisma generate && pnpm run start:dev"
    restart: unless-stopped
