services:
  api:
    build:
      context: .
      target: dev
    container_name: camerrideshare_api
    env_file:
      - .env
    environment:
      PORT: ${PORT:-3000}
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@host.docker.internal:5432/${POSTGRES_DB:-camerrideshare}?schema=public
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "pnpm prisma generate && pnpm prisma db push && pnpm prisma db seed && pnpm run start:dev"
    restart: unless-stopped
